### ISSUE TITLE
Front-End TASKS (in order... approximately)

### ISSUE THREAD

**Issue by JPDBrodeur** [thereeling/vacci-date#8]
## Sean
- Working on image upload (*clutch)

## John
- Set up Tailwind
- Hook up back-end mutations & queries (in utils)

## Ryan
- Final pages structure & routing

## Roundup on Sunday, 1/2/22
- Build re-usable components
- Back-end ENCORE: Finalize User Model

## Nick
- Configure global state (actions/reducers)
- Favicon

## Then start looking at this by Monday
- Conditional rendering of pages

## Corinne
- Styling :-) Go crazy, Corinne!

## Final Tasks
- Deploy to Heroku & MongoDB Atlas
- Prepare Presentation
- Polish README

**Comment by thereeling** [comment]
I'll create a new branch for state called feature/state.  I'll consult with group before I make a pull request to feature/front-end
